INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (1997,"Actual","Revenue","Operating Revenue",29181,0.195);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (1998,"Actual","Revenue","Operating Revenue",27911,0.197);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (1999,"Actual","Revenue","Operating Revenue",30645,0.203);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2000,"Actual","Revenue","Operating Revenue",31439,0.186);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2001,"Actual","Revenue","Operating Revenue",28496,0.178);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2002,"Actual","Revenue","Operating Revenue",25469,0.152);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2003,"Actual","Revenue","Operating Revenue",25315,0.145);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2004,"Actual","Revenue","Operating Revenue",27469,0.139);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2005,"Actual","Revenue","Operating Revenue",28171,0.129);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2006,"Actual","Revenue","Operating Revenue",31289,0.128);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2007,"Actual","Revenue","Operating Revenue",40375,0.145);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2008,"Actual","Revenue","Operating Revenue",41086,0.152);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2009,"Actual","Revenue","Operating Revenue",39547,0.134);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2010,"Actual","Revenue","Operating Revenue",46060,0.137);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2011,"Actual","Revenue","Operating Revenue",51077,0.143);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2012,"Actual","Revenue","Operating Revenue",55814,0.15);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2013,"Actual","Revenue","Operating Revenue",57020,0.147);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2014,"Actual","Revenue","Operating Revenue",60838,0.15);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2015,"Actual","Revenue","Operating Revenue",64823,0.152);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2016,"Actual","Revenue","Operating Revenue",68964,0.153);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2017,"Actual","Revenue","Operating Revenue",75816,0.158);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2018,"Actual","Revenue","Operating Revenue",73738,0.144);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2019,"Actual","Revenue","Operating Revenue",74274,0.146);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2020,"Revised","Revenue","Operating Revenue",64608,0.139);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2021,"Estimated","Revenue","Operating Revenue",76636,0.152);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (1997,"Actual","Revenue","Net Investment Income/Returns Contribution",0,0);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (1998,"Actual","Revenue","Net Investment Income/Returns Contribution",0,0);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (1999,"Actual","Revenue","Net Investment Income/Returns Contribution",0,0);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2000,"Actual","Revenue","Net Investment Income/Returns Contribution",2287,0.014);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2001,"Actual","Revenue","Net Investment Income/Returns Contribution",1375,0.009);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2002,"Actual","Revenue","Net Investment Income/Returns Contribution",3675,0.022);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2003,"Actual","Revenue","Net Investment Income/Returns Contribution",1900,0.011);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2004,"Actual","Revenue","Net Investment Income/Returns Contribution",3043,0.015);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2005,"Actual","Revenue","Net Investment Income/Returns Contribution",2777,0.013);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2006,"Actual","Revenue","Net Investment Income/Returns Contribution",2131,0.009);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2007,"Actual","Revenue","Net Investment Income/Returns Contribution",2405,0.009);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2008,"Actual","Revenue","Net Investment Income/Returns Contribution",4343,0.016);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2009,"Actual","Revenue","Net Investment Income/Returns Contribution",7006,0.024);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2010,"Actual","Revenue","Net Investment Income/Returns Contribution",7352,0.022);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2011,"Actual","Revenue","Net Investment Income/Returns Contribution",7916,0.022);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2012,"Actual","Revenue","Net Investment Income/Returns Contribution",7870,0.021);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2013,"Actual","Revenue","Net Investment Income/Returns Contribution",8289,0.021);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2014,"Actual","Revenue","Net Investment Income/Returns Contribution",8738,0.022);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2015,"Actual","Revenue","Net Investment Income/Returns Contribution",8943,0.021);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2016,"Actual","Revenue","Net Investment Income/Returns Contribution",14577,0.032);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2017,"Actual","Revenue","Net Investment Income/Returns Contribution",14724,0.031);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2018,"Actual","Revenue","Net Investment Income/Returns Contribution",16413,0.032);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2019,"Actual","Revenue","Net Investment Income/Returns Contribution",17038,0.033);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2020,"Revised","Revenue","Net Investment Income/Returns Contribution",18141,0.039);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2021,"Estimated","Revenue","Net Investment Income/Returns Contribution",19556,0.039);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (1997,"Actual","Expenditure","Total Expenditure",23043,0.154);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (1998,"Actual","Expenditure","Total Expenditure",26934,0.19);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (1999,"Actual","Expenditure","Total Expenditure",25079,0.167);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2000,"Actual","Expenditure","Total Expenditure",27908,0.165);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2001,"Actual","Expenditure","Total Expenditure",27305,0.171);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2002,"Actual","Expenditure","Total Expenditure",27152,0.162);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2003,"Actual","Expenditure","Total Expenditure",28499,0.163);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2004,"Actual","Expenditure","Total Expenditure",28957,0.146);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2005,"Actual","Expenditure","Total Expenditure",28634,0.131);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2006,"Actual","Expenditure","Total Expenditure",29905,0.123);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2007,"Actual","Expenditure","Total Expenditure",32982,0.119);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2008,"Actual","Expenditure","Total Expenditure",38091,0.141);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2009,"Actual","Expenditure","Total Expenditure",41891,0.142);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2010,"Actual","Expenditure","Total Expenditure",45338,0.135);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2011,"Actual","Expenditure","Total Expenditure",46563,0.131);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2012,"Actual","Expenditure","Total Expenditure",49004,0.132);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2013,"Actual","Expenditure","Total Expenditure",51728,0.133);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2014,"Actual","Expenditure","Total Expenditure",56648,0.14);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2015,"Actual","Expenditure","Total Expenditure",67447,0.158);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2016,"Actual","Expenditure","Total Expenditure",71045,0.158);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2017,"Actual","Expenditure","Total Expenditure",73556,0.153);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2018,"Actual","Expenditure","Total Expenditure",77824,0.152);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2019,"Actual","Expenditure","Total Expenditure",75337,0.148);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2020,"Revised","Expenditure","Total Expenditure",94056,0.202);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2021,"Estimated","Expenditure","Total Expenditure",102338,0.202);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (1997,"Actual","Expenditure","Special Transfers Excluding Top-ups to Endowment and Trust Funds",287,0.002);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (1998,"Actual","Expenditure","Special Transfers Excluding Top-ups to Endowment and Trust Funds",52,0);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (1999,"Actual","Expenditure","Special Transfers Excluding Top-ups to Endowment and Trust Funds",382,0.003);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2000,"Actual","Expenditure","Special Transfers Excluding Top-ups to Endowment and Trust Funds",1035,0.006);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2001,"Actual","Expenditure","Special Transfers Excluding Top-ups to Endowment and Trust Funds",3464,0.022);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2002,"Actual","Expenditure","Special Transfers Excluding Top-ups to Endowment and Trust Funds",1202,0.007);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2003,"Actual","Expenditure","Special Transfers Excluding Top-ups to Endowment and Trust Funds",603,0.003);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2004,"Actual","Expenditure","Special Transfers Excluding Top-ups to Endowment and Trust Funds",961,0.005);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2005,"Actual","Expenditure","Special Transfers Excluding Top-ups to Endowment and Trust Funds",579,0.003);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2006,"Actual","Expenditure","Special Transfers Excluding Top-ups to Endowment and Trust Funds",2622,0.011);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2007,"Actual","Expenditure","Special Transfers Excluding Top-ups to Endowment and Trust Funds",1342,0.005);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2008,"Actual","Expenditure","Special Transfers Excluding Top-ups to Endowment and Trust Funds",4089,0.015);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2009,"Actual","Expenditure","Special Transfers Excluding Top-ups to Endowment and Trust Funds",4071,0.014);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2010,"Actual","Expenditure","Special Transfers Excluding Top-ups to Endowment and Trust Funds",1505,0.004);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2011,"Actual","Expenditure","Special Transfers Excluding Top-ups to Endowment and Trust Funds",2909,0.008);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2012,"Actual","Expenditure","Special Transfers Excluding Top-ups to Endowment and Trust Funds",1458,0.004);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2013,"Actual","Expenditure","Special Transfers Excluding Top-ups to Endowment and Trust Funds",2990,0.008);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2014,"Actual","Expenditure","Special Transfers Excluding Top-ups to Endowment and Trust Funds",3856,0.01);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2015,"Actual","Expenditure","Special Transfers Excluding Top-ups to Endowment and Trust Funds",4369,0.01);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2016,"Actual","Expenditure","Special Transfers Excluding Top-ups to Endowment and Trust Funds",2772,0.006);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2017,"Actual","Expenditure","Special Transfers Excluding Top-ups to Endowment and Trust Funds",2112,0.004);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2018,"Actual","Expenditure","Special Transfers Excluding Top-ups to Endowment and Trust Funds",1689,0.003);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2019,"Actual","Expenditure","Special Transfers Excluding Top-ups to Endowment and Trust Funds",1561,0.003);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2020,"Revised","Expenditure","Special Transfers Excluding Top-ups to Endowment and Trust Funds",36269,0.078);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2021,"Estimated","Expenditure","Special Transfers Excluding Top-ups to Endowment and Trust Funds",4863,0.01);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (1997,"Actual","Expenditure","Top-ups to Endowment and Trust Funds",600,0.004);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (1998,"Actual","Expenditure","Top-ups to Endowment and Trust Funds",0,0);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (1999,"Actual","Expenditure","Top-ups to Endowment and Trust Funds",300,0.002);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2000,"Actual","Expenditure","Top-ups to Endowment and Trust Funds",800,0.005);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2001,"Actual","Expenditure","Top-ups to Endowment and Trust Funds",1800,0.011);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2002,"Actual","Expenditure","Top-ups to Endowment and Trust Funds",600,0.004);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2003,"Actual","Expenditure","Top-ups to Endowment and Trust Funds",0,0);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2004,"Actual","Expenditure","Top-ups to Endowment and Trust Funds",700,0.004);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2005,"Actual","Expenditure","Top-ups to Endowment and Trust Funds",250,0.001);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2006,"Actual","Expenditure","Top-ups to Endowment and Trust Funds",948,0.004);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2007,"Actual","Expenditure","Top-ups to Endowment and Trust Funds",800,0.003);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2008,"Actual","Expenditure","Top-ups to Endowment and Trust Funds",3010,0.011);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2009,"Actual","Expenditure","Top-ups to Endowment and Trust Funds",1410,0.005);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2010,"Actual","Expenditure","Top-ups to Endowment and Trust Funds",5590,0.017);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2011,"Actual","Expenditure","Top-ups to Endowment and Trust Funds",5517,0.015);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2012,"Actual","Expenditure","Top-ups to Endowment and Trust Funds",7402,0.02);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2013,"Actual","Expenditure","Top-ups to Endowment and Trust Funds",5594,0.014);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2014,"Actual","Expenditure","Top-ups to Endowment and Trust Funds",8500,0.021);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2015,"Actual","Expenditure","Top-ups to Endowment and Trust Funds",6000,0.014);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2016,"Actual","Expenditure","Top-ups to Endowment and Trust Funds",3600,0.008);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2017,"Actual","Expenditure","Top-ups to Endowment and Trust Funds",4010,0.008);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2018,"Actual","Expenditure","Top-ups to Endowment and Trust Funds",7300,0.014);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2019,"Actual","Expenditure","Top-ups to Endowment and Trust Funds",13568,0.027);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2020,"Revised","Expenditure","Top-ups to Endowment and Trust Funds",17320,0.037);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2021,"Estimated","Expenditure","Top-ups to Endowment and Trust Funds",0,0);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (1997,"Actual","Balance","Primary Balance",6139,0.041);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (1998,"Actual","Balance","Primary Balance",977,0.007);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (1999,"Actual","Balance","Primary Balance",5566,0.037);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2000,"Actual","Balance","Primary Balance",3531,0.021);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2001,"Actual","Balance","Primary Balance",1190,0.007);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2002,"Actual","Balance","Primary Balance",-1683,-0.01);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2003,"Actual","Balance","Primary Balance",-3184,-0.018);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2004,"Actual","Balance","Primary Balance",-1487,-0.007);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2005,"Actual","Balance","Primary Balance",-463,-0.002);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2006,"Actual","Balance","Primary Balance",1384,0.006);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2007,"Actual","Balance","Primary Balance",7393,0.027);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2008,"Actual","Balance","Primary Balance",2996,0.011);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2009,"Actual","Balance","Primary Balance",-2344,-0.008);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2010,"Actual","Balance","Primary Balance",722,0.002);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2011,"Actual","Balance","Primary Balance",4514,0.013);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2012,"Actual","Balance","Primary Balance",6811,0.018);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2013,"Actual","Balance","Primary Balance",5292,0.014);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2014,"Actual","Balance","Primary Balance",4190,0.01);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2015,"Actual","Balance","Primary Balance",-2624,-0.006);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2016,"Actual","Balance","Primary Balance",-2080,-0.005);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2017,"Actual","Balance","Primary Balance",2259,0.005);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2018,"Actual","Balance","Primary Balance",-4086,-0.008);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2019,"Actual","Balance","Primary Balance",-1063,-0.002);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2020,"Revised","Balance","Primary Balance",-29448,-0.063);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2021,"Estimated","Balance","Primary Balance",-25702,-0.051);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (1997,"Actual","Balance","Basic Balance",5852,0.039);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (1998,"Actual","Balance","Basic Balance",925,0.007);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (1999,"Actual","Balance","Basic Balance",5185,0.034);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2000,"Actual","Balance","Basic Balance",2496,0.015);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2001,"Actual","Balance","Basic Balance",-2273,-0.014);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2002,"Actual","Balance","Basic Balance",-2885,-0.017);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2003,"Actual","Balance","Basic Balance",-3788,-0.022);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2004,"Actual","Balance","Basic Balance",-2448,-0.012);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2005,"Actual","Balance","Basic Balance",-1041,-0.005);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2006,"Actual","Balance","Basic Balance",-1238,-0.005);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2007,"Actual","Balance","Basic Balance",6051,0.022);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2008,"Actual","Balance","Basic Balance",-1093,-0.004);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2009,"Actual","Balance","Basic Balance",-6416,-0.022);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2010,"Actual","Balance","Basic Balance",-782,-0.002);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2011,"Actual","Balance","Basic Balance",1605,0.005);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2012,"Actual","Balance","Basic Balance",5353,0.014);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2013,"Actual","Balance","Basic Balance",2303,0.006);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2014,"Actual","Balance","Basic Balance",334,0.001);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2015,"Actual","Balance","Basic Balance",-6993,-0.016);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2016,"Actual","Balance","Basic Balance",-4853,-0.011);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2017,"Actual","Balance","Basic Balance",147,0);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2018,"Actual","Balance","Basic Balance",-5774,-0.011);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2019,"Actual","Balance","Basic Balance",-2625,-0.005);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2020,"Revised","Balance","Basic Balance",-65716,-0.141);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2021,"Estimated","Balance","Basic Balance",-30566,-0.06);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (1997,"Actual","Balance","Overall Balance",5252,0.035);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (1998,"Actual","Balance","Overall Balance",925,0.007);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (1999,"Actual","Balance","Overall Balance",4885,0.032);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2000,"Actual","Balance","Overall Balance",3983,0.024);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2001,"Actual","Balance","Overall Balance",-2698,-0.017);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2002,"Actual","Balance","Overall Balance",191,0.001);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2003,"Actual","Balance","Overall Balance",-1887,-0.011);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2004,"Actual","Balance","Overall Balance",-105,-0.001);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2005,"Actual","Balance","Overall Balance",1486,0.007);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2006,"Actual","Balance","Overall Balance",-55,0);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2007,"Actual","Balance","Overall Balance",7656,0.028);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2008,"Actual","Balance","Overall Balance",239,0.001);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2009,"Actual","Balance","Overall Balance",-819,-0.003);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2010,"Actual","Balance","Overall Balance",980,0.003);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2011,"Actual","Balance","Overall Balance",4003,0.011);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2012,"Actual","Balance","Overall Balance",5821,0.016);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2013,"Actual","Balance","Overall Balance",4998,0.013);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2014,"Actual","Balance","Overall Balance",571,0.001);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2015,"Actual","Balance","Overall Balance",-4050,-0.009);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2016,"Actual","Balance","Overall Balance",6125,0.014);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2017,"Actual","Balance","Overall Balance",10861,0.023);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2018,"Actual","Balance","Overall Balance",3339,0.007);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2019,"Actual","Balance","Overall Balance",845,0.002);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2020,"Revised","Balance","Overall Balance",-64895,-0.139);
INSERT INTO position_fiscal (year,state,category,item,amount,percent) VALUES (2021,"Estimated","Balance","Overall Balance",-11010,-0.022);

